### PR TITLE
z3str3: negative lengths in get_len_value don't count

### LINKED ISSUE #2713: Assertion violation z3str3
Hi, 
For the following logic Z3 with `--smt.string_solver=z3str3` gives an assertion violation

```
(set-logic QF_S)
(declare-fun a () String)
(assert (= (str.indexof (str.++ "x" a) "y" 0) (str.indexof (str.++ a "x") "y" 2)))
(check-sat)
```

```
ASSERTION VIOLATION
File: ../src/util/rational.h
Line: 113
is_unsigned()
(C)ontinue, (A)bort, (S)top, (T)hrow exception, Invoke (G)DB
```
OS: Ubuntu 18.04
Revision: d95b549ff84b799e298f2f7db232499340460f05

### PR DESCRIPTION
**Pull request by mtrberzi**
Fixes #2713

### CODE REVIEW

File: src/smt/theory_str.cpp [hunk 1]
```diff
@@ -5062,7 +5062,7 @@ namespace smt {
         }
 
         TRACE("str", tout << "length of " << mk_ismt2_pp(e, m) << " is " << val << std::endl;);
-        return val.is_int();
+        return val.is_int() && val.is_nonneg();
```
Comment (NikolajBjorner) [inline src/smt/theory_str.cpp]: there is "val.is_unsigned()"
