### PR TITLE
Z3str3: fix empty-string contradictions

### LINKED ISSUE #2301: Z3str3 unsat answer for sat formula with indexOf
For the following formula, z3str3 returns unsat (version 4.8.4 and also the current master):
```(set-option :random-seed 0)
(set-option :produce-models true)
(set-info :status sat)
(declare-fun tmp_int2 () Int)
(assert
 (= (str.indexof "" "" tmp_int2) (- 1)))
(check-sat)
(get-value (tmp_int2))
```
 
If we set the smt.string_solver option to seq, then the result is sat (as expected) and a correct model is generated (tmp_int2 = -2).

### PR DESCRIPTION
**Pull request by mtrberzi**
Fixes #2301. Addresses cases where making the second argument to `str.indexof` the empty string (whether the literal or indirectly through a variable) caused contradictions and incorrect `UNSAT` answers.

### CODE REVIEW

**Comment by mtrberzi** [comment]
Great, build is passing now, ready for review.

File: src/smt/theory_str.cpp [hunk 1]
```diff
@@ -1385,8 +1397,12 @@ namespace smt {
         expr_ref reduceToIndex(ctx.mk_eq_atom(ex, indexAst), m);
         SASSERT(reduceToIndex);
 
-        expr_ref finalAxiom(m.mk_and(breakdownAssert, reduceToIndex), m);
-        SASSERT(finalAxiom);
+        expr_ref _finalAxiom(m.mk_and(breakdownAssert, reduceToIndex), m);
```
Comment (NikolajBjorner) [inline src/smt/theory_str.cpp]: leftover

File: src/smt/theory_str.cpp [hunk 2]
```diff
@@ -1436,6 +1452,8 @@ namespace smt {
 
         expr_ref minus_one(m_autil.mk_numeral(rational::minus_one(), true), m);
         expr_ref zero(m_autil.mk_numeral(rational::zero(), true), m);
+        expr_ref empty_string(mk_string(""), m);
+        th_rewriter rw(m);
```
Comment (NikolajBjorner) [inline src/smt/theory_str.cpp]: context has a rewriter

File: src/smt/theory_str.cpp [hunk 3]
```diff
@@ -1446,9 +1464,43 @@ namespace smt {
...
+        {
+            expr_ref premiseNEmpty(ctx.mk_eq_atom(N, empty_string), m);
+            // range check
+            expr_ref premiseRangeLower(m_autil.mk_le(i, minus_one), m);
+            expr_ref premiseRangeUpper(m_autil.mk_ge(m_autil.mk_add(i, m_autil.mk_mul(minus_one, mk_strlen(H))), zero), m);
+            expr_ref premiseRange(m.mk_or(premiseRangeLower, premiseRangeUpper), m);
+            expr_ref premise(m.mk_and(premiseNEmpty, premiseRange), m);
+            expr_ref conclusion(ctx.mk_eq_atom(e, minus_one), m);
+            expr_ref _finalAxiom(rewrite_implication(premise, conclusion), m);
+            expr_ref finalAxiom(_finalAxiom);
```
Comment (NikolajBjorner) [inline src/smt/theory_str.cpp]: not required to have both _finalAxiom and finalAxiom

File: src/smt/theory_str.cpp [hunk 4]
```diff
@@ -1446,9 +1464,43 @@ namespace smt {
...
+            assert_axiom(finalAxiom);
+        }
+
         // case 2: i = 0
         {
-            expr_ref premise(ctx.mk_eq_atom(i, zero), m);
+            expr_ref premise1(ctx.mk_eq_atom(i, zero), m);
+            expr_ref premise2(m.mk_not(ctx.mk_eq_atom(N, empty_string)), m);
+            expr_ref _premise(m.mk_and(premise1, premise2), m);
+            expr_ref premise(_premise);
```
Comment (NikolajBjorner) [inline src/smt/theory_str.cpp]: not required to have both _premise and premise

File: src/smt/theory_str.cpp [hunk 5]
```diff
@@ -1469,15 +1525,21 @@ namespace smt {
...
             expr_ref premise3(u.str.mk_contains(H, N), m);
-            expr_ref _premise(m.mk_and(premise1, premise2, premise3), m);
+            expr_ref premise4(m.mk_not(ctx.mk_eq_atom(N, mk_string(""))), m);
+
+            expr_ref_vector premises(m);
+            premises.push_back(premise1);
+            premises.push_back(premise2);
+            premises.push_back(premise3);
+            premises.push_back(premise4);
+            expr_ref _premise(mk_and(premises), m);
```
Comment (NikolajBjorner) [inline src/smt/theory_str.cpp]: not required to have both _premise and premise
