### PR TITLE
x64 clause allocator bug fix

### LINKED ISSUE #436: AddressSanitizer is reporting problems running the c_example
On current master (eae17a43a2dc66b99d12c7596044b82b933760fa) when I build Z3 using Clang 3.7.1 and the address sanitizer and run the C-examples it reports problems.

I've tried two different configurations so far. Both have problems.

# OpenMP disabled: Reports use after free

```bash
mkdir build_asan
CXX=clang++ CC=clang CXXFLAGS="-fno-omit-frame-pointer -fsanitize=address" LDFLAGS="-fsanitize=address" python scripts/mk_make.py --build build_asan --noomp --debug --prefix /home/dsl11/dev/klee/z3/install_asan
cd build_asan
make -j8
make c_example
```

Now run the example

```
LD_LIBRARY_PATH=`pwd` ./c_example 

<snip>

bitvector_example2
find values of x and y, such that x ^ y - 103 == x * y
=================================================================
==5415==ERROR: AddressSanitizer: heap-use-after-free on address 0x60400005ff54 at pc 0x7fa75457de89 bp 0x7ffde39cdbf0 sp 0x7ffde39cdbe8
READ of size 4 at 0x60400005ff54 thread T0
    #0 0x7fa75457de88 in sat::clause::operator[](unsigned int) /home/dsl11/dev/klee/z3/z3_upstream/build_asan/../src/sat/sat_clause.h:59:46
    #1 0x7fa7545664a5 in sat::solver::resolve_conflict_core() /home/dsl11/dev/klee/z3/z3_upstream/build_asan/../src/sat/sat_solver.cpp:1690:21
    #2 0x7fa754559a1c in sat::solver::resolve_conflict() /home/dsl11/dev/klee/z3/z3_upstream/build_asan/../src/sat/sat_solver.cpp:1621:22
    #3 0x7fa75455651f in sat::solver::bounded_search() /home/dsl11/dev/klee/z3/z3_upstream/build_asan/../src/sat/sat_solver.cpp:844:22
    #4 0x7fa754554997 in sat::solver::check(unsigned int, sat::literal const*, double const*, double) /home/dsl11/dev/klee/z3/z3_upstream/build_asan/../src/sat/sat_solver.cpp:736:27
    #5 0x7fa753e09d29 in sat::solver::check(unsigned int, sat::literal const*) /home/dsl11/dev/klee/z3/z3_upstream/build_asan/../src/sat/sat_solver.h:280:20
    #6 0x7fa753e08654 in sat_tactic::imp::operator()(ref<goal> const&, sref_buffer<goal, 16u>&, ref<model_converter>&, ref<proof_converter>&, obj_ref<dependency_manager<ast_manager::expr_dependency_config>::dependency, ast_manager>&) /home/dsl11/dev/klee/z3/z3_upstream/build_asan/../src/sat/tactic/sat_tactic.cpp:72:23
    #7 0x7fa753e06f69 in sat_tactic::operator()(ref<goal> const&, sref_buffer<goal, 16u>&, ref<model_converter>&, ref<proof_converter>&, obj_ref<dependency_manager<ast_manager::expr_dependency_config>::dependency, ast_manager>&) /home/dsl11/dev/klee/z3/z3_upstream/build_asan/../src/sat/tactic/sat_tactic.cpp:192:13
    #8 0x7fa753f7d335 in cleanup_tactical::operator()(ref<goal> const&, sref_buffer<goal, 16u>&, ref<model_converter>&, ref<proof_converter>&, obj_ref<dependency_manager<ast_manager::expr_dependency_config>::dependency, ast_manager>&) /home/dsl11/dev/klee/z3/z3_upstream/build_asan/../src/tactic/tactical.cpp:1124:9
    #9 0x7fa753f7ee6d in cond_tactical::operator()(ref<goal> const&, sref_buffer<goal, 16u>&, ref<model_converter>&, ref<proof_converter>&, obj_ref<dependency_manager<ast_manager::expr_dependency_config>::dependency, ast_manager>&) /home/dsl11/dev/klee/z3/z3_upstream/build_asan/../src/tactic/tactical.cpp:1255:13
    #10 0x7fa753f67828 in and_then_tactical::operator()(ref<goal> const&, sref_buffer<goal, 16u>&, ref<model_converter>&, ref<proof_converter>&, obj_ref<dependency_manager<ast_manager::expr_dependency_config>::dependency, ast_manager>&) /home/dsl11/dev/klee/z3/z3_upstream/build_asan/../src/tactic/tactical.cpp:140:13
    #11 0x7fa753f67828 in and_then_tactical::operator()(ref<goal> const&, sref_buffer<goal, 16u>&, ref<model_converter>&, ref<proof_converter>&, obj_ref<dependency_manager<ast_manager::expr_dependency_config>::dependency, ast_manager>&) /home/dsl11/dev/klee/z3/z3_upstream/build_asan/../src/tactic/tactical.cpp:140:13
    #12 0x7fa753f7ee6d in cond_tactical::operator()(ref<goal> const&, sref_buffer<goal, 16u>&, ref<model_converter>&, ref<proof_converter>&, obj_ref<dependency_manager<ast_manager::expr_dependency_config>::dependency, ast_manager>&) /home/dsl11/dev/klee/z3/z3_upstream/build_asan/../src/tactic/tactical.cpp:1255:13
    #13 0x7fa753f7ed9a in cond_tactical::operator()(ref<goal> const&, sref_buffer<goal, 16u>&, ref<model_converter>&, ref<proof_converter>&, obj_ref<dependency_manager<ast_manager::expr_dependency_config>::dependency, ast_manager>&) /home/dsl11/dev/klee/z3/z3_upstream/build_asan/../src/tactic/tactical.cpp:1253:13
    #14 0x7fa753f67828 in and_then_tactical::operator()(ref<goal> const&, sref_buffer<goal, 16u>&, ref<model_converter>&, ref<proof_converter>&, obj_ref<dependency_manager<ast_manager::expr_dependency_config>::dependency, ast_manager>&) /home/dsl11/dev/klee/z3/z3_upstream/build_asan/../src/tactic/tactical.cpp:140:13
    #15 0x7fa753f7aa0b in unary_tactical::operator()(ref<goal> const&, sref_buffer<goal, 16u>&, ref<model_converter>&, ref<proof_converter>&, obj_ref<dependency_manager<ast_manager::expr_dependency_config>::dependency, ast_manager>&) /home/dsl11/dev/klee/z3/z3_upstream/build_asan/../src/tactic/tactical.cpp:915:9
    #16 0x7fa753f7ed9a in cond_tactical::operator()(ref<goal> const&, sref_buffer<goal, 16u>&, ref<model_converter>&, ref<proof_converter>&, obj_ref<dependency_manager<ast_manager::expr_dependency_config>::dependency, ast_manager>&) /home/dsl11/dev/klee/z3/z3_upstream/build_asan/../src/tactic/tactical.cpp:1253:13
    #17 0x7fa753f67828 in and_then_tactical::operator()(ref<goal> const&, sref_buffer<goal, 16u>&, ref<model_converter>&, ref<proof_converter>&, obj_ref<dependency_manager<ast_manager::expr_dependency_config>::dependency, ast_manager>&) /home/dsl11/dev/klee/z3/z3_upstream/build_asan/../src/tactic/tactical.cpp:140:13
    #18 0x7fa753f7aa0b in unary_tactical::operator()(ref<goal> const&, sref_buffer<goal, 16u>&, ref<model_converter>&, ref<proof_converter>&, obj_ref<dependency_manager<ast_manager::expr_dependency_config>::dependency, ast_manager>&) /home/dsl11/dev/klee/z3/z3_upstream/build_asan/../src/tactic/tactical.cpp:915:9
    #19 0x7fa753fb36f4 in exec(tactic&, ref<goal> const&, sref_buffer<goal, 16u>&, ref<model_converter>&, ref<proof_converter>&, obj_ref<dependency_manager<ast_manager::expr_dependency_config>::dependency, ast_manager>&) /home/dsl11/dev/klee/z3/z3_upstream/build_asan/../src/tactic/tactic.cpp:167:9
    #20 0x7fa753fb3d8b in check_sat(tactic&, ref<goal>&, ref<model>&, obj_ref<app, ast_manager>&, obj_ref<dependency_manager<ast_manager::expr_dependency_config>::dependency, ast_manager>&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) /home/dsl11/dev/klee/z3/z3_upstream/build_asan/../src/tactic/tactic.cpp:189:9
    #21 0x7fa753c0e5bf in tactic2solver::check_sat_core(unsigned int, expr* const*) /home/dsl11/dev/klee/z3/z3_upstream/build_asan/../src/solver/tactic2solver.cpp:148:17
    #22 0x7fa753c15f4d in solver_na2as::check_sat(unsigned int, expr* const*) /home/dsl11/dev/klee/z3/z3_upstream/build_asan/../src/solver/solver_na2as.cpp:67:12
    #23 0x7fa753c13c76 in combined_solver::check_sat(unsigned int, expr* const*) /home/dsl11/dev/klee/z3/z3_upstream/build_asan/../src/solver/combined_solver.cpp:232:16
    #24 0x7fa75234834d in _solver_check(_Z3_context*, _Z3_solver*, unsigned int, _Z3_ast* const*) /home/dsl11/dev/klee/z3/z3_upstream/build_asan/../src/api/api_solver.cpp:282:26
    #25 0x7fa752347d3b in Z3_solver_check /home/dsl11/dev/klee/z3/z3_upstream/build_asan/../src/api/api_solver.cpp:297:16
    #26 0x4dfbe7 in check /home/dsl11/dev/klee/z3/z3_upstream/build_asan/../examples/c/test_capi.c:202:23
    #27 0x4e543c in bitvector_example2 /home/dsl11/dev/klee/z3/z3_upstream/build_asan/../examples/c/test_capi.c:1454:5
    #28 0x4f0428 in main /home/dsl11/dev/klee/z3/z3_upstream/build_asan/../examples/c/test_capi.c:2810:5
    #29 0x7fa750a4160f in __libc_start_main (/usr/lib/libc.so.6+0x2060f)
    #30 0x41adf8 in _start (/home/dsl11/dev/klee/z3/z3_upstream/build_asan/c_example+0x41adf8)

0x60400005ff54 is located 4 bytes inside of 40-byte region [0x60400005ff50,0x60400005ff78)
freed by thread T0 here:
    #0 0x4b0c20 in __interceptor_cfree.localalias.1 (/home/dsl11/dev/klee/z3/z3_upstream/build_asan/c_example+0x4b0c20)
    #1 0x7fa754809925 in memory::deallocate(void*) /home/dsl11/dev/klee/z3/z3_upstream/build_asan/../src/util/memory_manager.cpp:268:5
    #2 0x7fa752385d85 in void dealloc<tactic>(tactic*) /home/dsl11/dev/klee/z3/z3_upstream/build_asan/../src/util/memory_manager.h:95:5
    #3 0x7fa752385cf8 in tactic::dec_ref() /home/dsl11/dev/klee/z3/z3_upstream/build_asan/../src/tactic/tactic.h:43:85
    #4 0x7fa753f697ae in binary_tactical::~binary_tactical() /home/dsl11/dev/klee/z3/z3_upstream/build_asan/../src/tactic/tactical.cpp:43:9
    #5 0x7fa753f66a74 in and_then_tactical::~and_then_tactical() /home/dsl11/dev/klee/z3/z3_upstream/build_asan/../src/tactic/tactical.cpp:107:35
    #6 0x7fa752385d79 in void dealloc<tactic>(tactic*) /home/dsl11/dev/klee/z3/z3_upstream/build_asan/../src/util/memory_manager.h:94:5
    #7 0x7fa752385cf8 in tactic::dec_ref() /home/dsl11/dev/klee/z3/z3_upstream/build_asan/../src/tactic/tactic.h:43:85
    #8 0x7fa753f697e8 in binary_tactical::~binary_tactical() /home/dsl11/dev/klee/z3/z3_upstream/build_asan/../src/tactic/tactical.cpp:44:9
    #9 0x7fa753f66a74 in and_then_tactical::~and_then_tactical() /home/dsl11/dev/klee/z3/z3_upstream/build_asan/../src/tactic/tactical.cpp:107:35
    #10 0x7fa752385d79 in void dealloc<tactic>(tactic*) /home/dsl11/dev/klee/z3/z3_upstream/build_asan/../src/util/memory_manager.h:94:5
    #11 0x7fa752385cf8 in tactic::dec_ref() /home/dsl11/dev/klee/z3/z3_upstream/build_asan/../src/tactic/tactic.h:43:85
    #12 0x7fa753f697e8 in binary_tactical::~binary_tactical() /home/dsl11/dev/klee/z3/z3_upstream/build_asan/../src/tactic/tactical.cpp:44:9
    #13 0x7fa753f66a74 in and_then_tactical::~and_then_tactical() /home/dsl11/dev/klee/z3/z3_upstream/build_asan/../src/tactic/tactical.cpp:107:35
    #14 0x7fa752385d79 in void dealloc<tactic>(tactic*) /home/dsl11/dev/klee/z3/z3_upstream/build_asan/../src/util/memory_manager.h:94:5
    #15 0x7fa752385cf8 in tactic::dec_ref() /home/dsl11/dev/klee/z3/z3_upstream/build_asan/../src/tactic/tactic.h:43:85
    #16 0x7fa753f697e8 in binary_tactical::~binary_tactical() /home/dsl11/dev/klee/z3/z3_upstream/build_asan/../src/tactic/tactical.cpp:44:9
    #17 0x7fa753f66a74 in and_then_tactical::~and_then_tactical() /home/dsl11/dev/klee/z3/z3_upstream/build_asan/../src/tactic/tactical.cpp:107:35
    #18 0x7fa752385d79 in void dealloc<tactic>(tactic*) /home/dsl11/dev/klee/z3/z3_upstream/build_asan/../src/util/memory_manager.h:94:5
    #19 0x7fa752385cf8 in tactic::dec_ref() /home/dsl11/dev/klee/z3/z3_upstream/build_asan/../src/tactic/tactic.h:43:85
    #20 0x7fa753f6cc8c in nary_tactical::~nary_tactical() /home/dsl11/dev/klee/z3/z3_upstream/build_asan/../src/tactic/tactical.cpp:289:13
    #21 0x7fa753f6b864 in or_else_tactical::~or_else_tactical() /home/dsl11/dev/klee/z3/z3_upstream/build_asan/../src/tactic/tactical.cpp:371:34
    #22 0x7fa752385d79 in void dealloc<tactic>(tactic*) /home/dsl11/dev/klee/z3/z3_upstream/build_asan/../src/util/memory_manager.h:94:5
    #23 0x7fa752385cf8 in tactic::dec_ref() /home/dsl11/dev/klee/z3/z3_upstream/build_asan/../src/tactic/tactic.h:43:85
    #24 0x7fa753f697e8 in binary_tactical::~binary_tactical() /home/dsl11/dev/klee/z3/z3_upstream/build_asan/../src/tactic/tactical.cpp:44:9
    #25 0x7fa753f66a74 in and_then_tactical::~and_then_tactical() /home/dsl11/dev/klee/z3/z3_upstream/build_asan/../src/tactic/tactical.cpp:107:35
    #26 0x7fa752385d79 in void dealloc<tactic>(tactic*) /home/dsl11/dev/klee/z3/z3_upstream/build_asan/../src/util/memory_manager.h:94:5
    #27 0x7fa752385cf8 in tactic::dec_ref() /home/dsl11/dev/klee/z3/z3_upstream/build_asan/../src/tactic/tactic.h:43:85
    #28 0x7fa753f697e8 in binary_tactical::~binary_tactical() /home/dsl11/dev/klee/z3/z3_upstream/build_asan/../src/tactic/tactical.cpp:44:9
    #29 0x7fa753f66a74 in and_then_tactical::~and_then_tactical() /home/dsl11/dev/klee/z3/z3_upstream/build_asan/../src/tactic/tactical.cpp:107:35

previously allocated by thread T0 here:
    #0 0x4b0da8 in __interceptor_malloc (/home/dsl11/dev/klee/z3/z3_upstream/build_asan/c_example+0x4b0da8)
    #1 0x7fa754809a90 in memory::allocate(unsigned long) /home/dsl11/dev/klee/z3/z3_upstream/build_asan/../src/util/memory_manager.cpp:276:16
    #2 0x7fa753f657ae in using_params(tactic*, params_ref const&) /home/dsl11/dev/klee/z3/z3_upstream/build_asan/../src/tactic/tactical.cpp:1195:12
    #3 0x7fa753c5400f in mk_qfnra_nlsat_tactic(ast_manager&, params_ref const&) /home/dsl11/dev/klee/z3/z3_upstream/build_asan/../src/nlsat/tactic/qfnra_nlsat_tactic.cpp:56:30
    #4 0x7fa7525c6da6 in mk_qfnra_tactic(ast_manager&, params_ref const&) /home/dsl11/dev/klee/z3/z3_upstream/build_asan/../src/tactic/smtlogics/qfnra_tactic.cpp:50:29
    #5 0x7fa75258f092 in mk_qffp_tactic(ast_manager&, params_ref const&) /home/dsl11/dev/klee/z3/z3_upstream/build_asan/../src/tactic/fpa/qffp_tactic.cpp:84:38
    #6 0x7fa7525474bb in mk_default_tactic(ast_manager&, params_ref const&) /home/dsl11/dev/klee/z3/z3_upstream/build_asan/../src/tactic/portfolio/default_tactic.cpp:46:66
    #7 0x7fa752545ed0 in mk_tactic_for_logic(ast_manager&, params_ref const&, symbol const&) /home/dsl11/dev/klee/z3/z3_upstream/build_asan/../src/tactic/portfolio/smt_strategic_solver.cpp:94:16
    #8 0x7fa752546907 in smt_strategic_solver_factory::operator()(ast_manager&, params_ref const&, bool, bool, bool, symbol const&) /home/dsl11/dev/klee/z3/z3_upstream/build_asan/../src/tactic/portfolio/smt_strategic_solver.cpp:116:22
    #9 0x7fa75234b339 in init_solver_core(_Z3_context*, _Z3_solver*) /home/dsl11/dev/klee/z3/z3_upstream/build_asan/../src/api/api_solver.cpp:43:23
    #10 0x7fa75234409b in init_solver(_Z3_context*, _Z3_solver*) /home/dsl11/dev/klee/z3/z3_upstream/build_asan/../src/api/api_solver.cpp:54:13
    #11 0x7fa752346cb7 in Z3_solver_assert /home/dsl11/dev/klee/z3/z3_upstream/build_asan/../src/api/api_solver.cpp:231:9
    #12 0x4e3065 in prove_example2 /home/dsl11/dev/klee/z3/z3_upstream/build_asan/../examples/c/test_capi.c:956:5
    #13 0x4f0400 in main /home/dsl11/dev/klee/z3/z3_upstream/build_asan/../examples/c/test_capi.c:2802:5
    #14 0x7fa750a4160f in __libc_start_main (/usr/lib/libc.so.6+0x2060f)

SUMMARY: AddressSanitizer: heap-use-after-free /home/dsl11/dev/klee/z3/z3_upstream/build_asan/../src/sat/sat_clause.h:59:46 in sat::clause::operator[](unsigned int)
Shadow bytes around the buggy address:
  0x0c0880003f90: fa fa fd fd fd fd fd fa fa fa fd fd fd fd fd fa
  0x0c0880003fa0: fa fa fd fd fd fd fd fa fa fa fd fd fd fd fd fa
  0x0c0880003fb0: fa fa fd fd fd fd fd fa fa fa fd fd fd fd fd fa
  0x0c0880003fc0: fa fa fd fd fd fd fd fa fa fa fd fd fd fd fd fa
  0x0c0880003fd0: fa fa fd fd fd fd fd fa fa fa fd fd fd fd fd fa
=>0x0c0880003fe0: fa fa fd fd fd fd fd fa fa fa[fd]fd fd fd fd fa
  0x0c0880003ff0: fa fa fd fd fd fd fd fa fa fa fd fd fd fd fd fa
  0x0c0880004000: fa fa fd fd fd fd fd fa fa fa fd fd fd fd fd fa
  0x0c0880004010: fa fa fd fd fd fd fd fa fa fa fd fd fd fd fd fa
  0x0c0880004020: fa fa fd fd fd fd fd fa fa fa fd fd fd fd fd fa
  0x0c0880004030: fa fa fd fd fd fd fd fa fa fa fd fd fd fd fd fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Heap right redzone:      fb
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack partial redzone:   f4
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==5415==ABORTING
```

# OpenMP enabled: SEGFAULT (looks like a nullptr dereference)

On my system I have to install the LLVM OpenMP implementation (``openmp`` package on Arch Linux) for Clang to be able to build OpenMP code.

```bash
CXX=clang++ CC=clang CXXFLAGS="-fno-omit-frame-pointer -fsanitize=address" LDFLAGS="-fsanitize=address" python scripts/mk_make.py --build build_asan_openmp --debug --prefix /home/dsl11/dev/klee/z3/install_asan
cd build_asan_openmp
make -j8
make c_example
```

```
LD_LIBRARY_PATH=`pwd` ./c_example
Z3 4.4.2.0

simple_example
ASAN:SIGSEGV
=================================================================
==8377==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x7f7253ef0c23 bp 0x7ffccd309870 sp 0x7ffccd309830 T0)
    #0 0x7f7253ef0c22 in memory::deallocate(void*) /home/dsl11/dev/klee/z3/z3_upstream/build_asan_openmp/../src/util/memory_manager.cpp:265:22
    #1 0x7f7252040fd1 in buffer<unsigned int, false, 16u>::free_memory() /home/dsl11/dev/klee/z3/z3_upstream/build_asan_openmp/../src/util/buffer.h:35:9
    #2 0x7f7252040f54 in buffer<unsigned int, false, 16u>::destroy() /home/dsl11/dev/klee/z3/z3_upstream/build_asan_openmp/../src/util/buffer.h:60:9
    #3 0x7f72520259f4 in buffer<unsigned int, false, 16u>::~buffer() /home/dsl11/dev/klee/z3/z3_upstream/build_asan_openmp/../src/util/buffer.h:95:9
    #4 0x7f72523de104 in sbuffer<unsigned int, 16u>::~sbuffer() /home/dsl11/dev/klee/z3/z3_upstream/build_asan_openmp/../src/util/buffer.h:254:7
    #5 0x7f7253f42834 in mpn_manager::mpn_sbuffer::~mpn_sbuffer() /home/dsl11/dev/klee/z3/z3_upstream/build_asan_openmp/../src/util/mpn.h:65:12
    #6 0x7f7253f3b81f in mpn_manager::~mpn_manager() /home/dsl11/dev/klee/z3/z3_upstream/build_asan_openmp/../src/util/mpn.cpp:37:1
    #7 0x7f7253eb6cc4 in mpz_manager<false>::~mpz_manager() /home/dsl11/dev/klee/z3/z3_upstream/build_asan_openmp/../src/util/mpz.cpp:162:1
    #8 0x7f7253ecd24c in mpq_manager<false>::~mpq_manager() /home/dsl11/dev/klee/z3/z3_upstream/build_asan_openmp/../src/util/mpq.cpp:35:1
    #9 0x7f7251ae95da in api::context::~context() /home/dsl11/dev/klee/z3/z3_upstream/build_asan_openmp/../src/api/api_context.cpp:109:5
    #10 0x7f7251af0c54 in void dealloc<api::context>(api::context*) /home/dsl11/dev/klee/z3/z3_upstream/build_asan_openmp/../src/util/memory_manager.h:94:5
    #11 0x7f7251aebd1a in Z3_del_context /home/dsl11/dev/klee/z3/z3_upstream/build_asan_openmp/../src/api/api_context.cpp:354:9
    #12 0x4e1e66 in simple_example /home/dsl11/dev/klee/z3/z3_upstream/build_asan_openmp/../examples/c/test_capi.c:704:5
    #13 0x4f03f7 in main /home/dsl11/dev/klee/z3/z3_upstream/build_asan_openmp/../examples/c/test_capi.c:2797:5
    #14 0x7f724ff0660f in __libc_start_main (/usr/lib/libc.so.6+0x2060f)
    #15 0x41ae08 in _start (/home/dsl11/dev/klee/z3/z3_upstream/build_asan_openmp/c_example+0x41ae08)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /home/dsl11/dev/klee/z3/z3_upstream/build_asan_openmp/../src/util/memory_manager.cpp:265:22 in memory::deallocate(void*)
==8377==ABORTING

```

### PR DESCRIPTION
**Pull request by wintersteiger**
This should fix #436 and #712, at least in debug mode, and it replaces #715.

### CODE REVIEW

File: src/sat/sat_clause.cpp [hunk 1]
```diff
@@ -123,53 +123,80 @@ namespace sat {
...
+#if defined(_AMD64_) 
         m_num_segments = 0;
 #endif
     }
 
     clause * clause_allocator::get_clause(clause_offset cls_off) const {
-#ifdef _AMD64_
-        return reinterpret_cast<clause *>(m_segments[cls_off & c_aligment_mask] + (static_cast<size_t>(cls_off) & ~c_aligment_mask));
+#if defined(_AMD64_) 
+#if defined (Z3DEBUG)
```
Comment (delcypher) [inline src/sat/sat_clause.cpp]: This really deserves a comment explaining why we are doing this (i.e. mention ASan).

File: src/sat/sat_clause.cpp [hunk 2]
```diff
@@ -123,53 +123,80 @@ namespace sat {
...
+        clause const* result;
+        if (((cls_off & c_alignment_mask) == c_last_segment)) { 
+            unsigned id = cls_off >> c_cls_alignment;
+            bool check = m_last_seg_id2cls.find(id, result);
+            SASSERT(check);
+            return const_cast<clause*>(result);
+        }
+#endif
+        return reinterpret_cast<clause *>(m_segments[cls_off & c_alignment_mask] + (static_cast<size_t>(cls_off) & ~c_alignment_mask));
```
Comment (delcypher) [inline src/sat/sat_clause.cpp]: Again could really do with a comment here explaining we are mapping a 32-bit integer to a `clause*`.

File: src/sat/sat_clause.cpp [hunk 3]
```diff
@@ -123,53 +123,80 @@ namespace sat {
...
+        size_t ptr = reinterpret_cast<size_t>(cls);
+
+        SASSERT((ptr & c_alignment_mask) == 0);
+        ptr &= 0xFFFFFFFF00000000ull; // Keep only high part
         unsigned i = 0;
         for (i = 0; i < m_num_segments; ++i)
-            if (m_segments[i] == ptr)
-                return i;
+          if (m_segments[i] == ptr) 
+            return i;
```
Comment (delcypher) [inline src/sat/sat_clause.cpp]: Minor nit: Indentation here is wrong for the `return i`.

File: src/sat/sat_clause.cpp [hunk 4]
```diff
@@ -123,53 +123,80 @@ namespace sat {
...
         i = m_num_segments;
-        m_num_segments++;
-        SASSERT(m_num_segments <= c_max_segments);
-        if (i >= c_max_segments)
+#if defined(Z3DEBUG)
+        SASSERT(i <= c_last_segment);
```
Comment (delcypher) [inline src/sat/sat_clause.cpp]: The `SASSERT(i <= c_last_segment)` is the same for both `#if .. #else` blocks so I'd recommend hoisting it out to avoid code duplication and for clarity.

File: src/sat/sat_clause.cpp [hunk 5]
```diff
@@ -123,53 +123,80 @@ namespace sat {
...
+            if (!m_last_seg_id2cls.contains(cls->id()))
+                m_last_seg_id2cls.insert(cls->id(), cls);
+        }
+        else {
+            ++m_num_segments;
+            m_segments[i] = ptr;
+        }
+#else
+        SASSERT(i <= c_last_segment);
+        if (i == c_last_segment) {
```
Comment (delcypher) [inline src/sat/sat_clause.cpp]: This condition is not the same as it was in the old code because `c_last_segment ==  c_max_segments -1`. This means we never use the last segment. Is this intentional?

File: src/sat/sat_clause.cpp [hunk 6]
```diff
@@ -123,53 +123,80 @@ namespace sat {
...
+        return static_cast<unsigned>(reinterpret_cast<size_t>(cls)) + segment;
 #else
-        return reinterpret_cast<size_t>(ptr);
+        return reinterpret_cast<size_t>(cls);
 #endif
     }
     
     clause * clause_allocator::mk_clause(unsigned num_lits, literal const * lits, bool learned) {
         size_t size = clause::get_obj_size(num_lits);
-#ifdef _AMD64_
```
Comment (delcypher) [inline src/sat/sat_clause.cpp]: Why is this code being removed?

File: src/sat/sat_clause.cpp [hunk 7]
```diff
@@ -181,12 +208,6 @@ namespace sat {
         TRACE("sat", tout << "delete: " << cls->id() << " " << cls << " " << *cls << "\n";);
         m_id_gen.recycle(cls->id());
         size_t size = clause::get_obj_size(cls->m_capacity);
-#ifdef _AMD64_
```
Comment (delcypher) [inline src/sat/sat_clause.cpp]: Why is this code being removed?

File: src/sat/sat_clause.h [hunk 8]
```diff
@@ -124,13 +125,16 @@ namespace sat {
...
         static const unsigned  c_cls_alignment = 3; 
-        static const unsigned  c_max_segments  = 1 << c_cls_alignment;
-        static const size_t    c_aligment_mask = (1ull << c_cls_alignment) - 1ull;
+        static const unsigned  c_last_segment  = (1ull << c_cls_alignment) - 1ull;
+        static const size_t    c_alignment_mask = (1ull << c_cls_alignment) - 1ull;
         unsigned               m_num_segments;
-        size_t                 m_segments[c_max_segments];
+        size_t                 m_segments[c_last_segment];
+#if defined(Z3DEBUG)
+        u_map<clause const*>   m_last_seg_id2cls;
```
Comment (delcypher) [inline src/sat/sat_clause.h]: Suggested comment:

```
u_map<clause const*>   m_last_seg_id2cls; // Fallback to this when segments are exhausted. Useful for ASan builds.
```

**Comment by delcypher** [comment]
@wintersteiger I've done a quick skim through this and left comments. I've not yet tested this but I will report back when I've done so. A higher level comment I'd like to make is that I'd like to see a better commit message. I find

```
x64 clause allocator bug fix
```

far too terse. I'd like to see an explanation of why this change is being made (i.e. for ASan). It also doesn't (and it really should) explain this will only fix debug builds. This information is really useful when using `git log` and `git blame`.

**Comment by wintersteiger** [comment]
Re: ASan comments: This fix was a proper fix for a real bug in both, debug and release mode, not a workaround to silence a false positive from ASan. And yes, the last segment is not used in release mode, which means that debug and release mode will have the same behaviour as long as the number of segments doesn't exceed the limit. Feel free to add +1's everywhere if that bugs you though.

**Comment by delcypher** [comment]
@wintersteiger I've built your branch with ASan (Clang 3.9) and it fixes the problem with running `c_example` (LeakSanitizer fires at the end but I think its a false positive). I've also tried running it against KLEE built with ASan and everything seems fine :)

> Re: ASan comments: This fix was a proper fix for a real bug in both, debug and release mode, not a workaround to silence a false positive from ASan.

What bug where you specifically trying to fix? There's lot of behavioural changes here. 

> And yes, the last segment is not used in release mode, which means that debug and release mode will have the same behaviour as long as the number of segments doesn't exceed the limit. Feel free to add +1's everywhere if that bugs you though.

It's up to you but I find this a slightly odd choice (allocating space for a segment that will never be used). You could just write the code to use all the segments.

I also don't understand the rationale of having the hashmap fallback in the debug build but in release mode raising an exception. Wouldn't it be better to just fall back to the hashmap in all builds?

I don't want to hold up this change getting into master though because I really need ASan builds to work so feel free to merge this change and iterate on my suggestions. Also note that your changes no longer merge cleanly with master.

**Comment by wintersteiger** [comment]
That's great, thanks for the additional tests!

The bug was that the last segment would overflow into pointers of the form ...1000, so clauses from segment #8 looked like they were from segment #0, which then triggered assertion failures as the clauses obtained from segmented pointers wouldn't contain what was expected.

The fixed code _does_ use all segments, but only in debug mode. The last segment is a "debug" segment which simulates an arbitrary number of segments by storing them in a hashmap. This is purely for debugging purposes; in release mode this would defeat the purpose, because it would introduce unnecessary overhead (just keeping the non-segmented pointers would be more efficient). Sure, we can make the release version use that last segment (but without a hashmap) once we are confident everything works as expected. The exception is the same as before, except it may throw it one segment earlier now.

**Comment by wintersteiger** [comment]
(rebased)
