### PR TITLE
Fix #2736

### LINKED ISSUE #2736: [Consolidated] Soundness bugs in z3str3
Hi,
on the following unsatisfiable formula z3str3 incorrectly reports "sat" 

```
(declare-fun i () Int)
(assert (< i 1))
(assert (= (int.to.str i) "00"))
(check-sat)
```

OS: Ubuntu 18.04
Revision: ba03d99

### PR DESCRIPTION
**Pull request by FedericoAureliano**
Issue #2736 exploits that the translation from a string to an int in finalcheck_int2str ignores leading zeros. The fix is to enforce that int.to.str does not produce a string with a prefix of "0", unless the string is "0".

### CODE REVIEW

**Comment by NikolajBjorner** [comment]
@mtrberzi - can you review and comment/sign off?

**Comment by mtrberzi** [comment]
@NikolajBjorner will do - Federico and I have been discussing this fix in an email thread. I need to double-check the axiom as it might need to change slightly.

File: src/smt/theory_str.cpp [hunk 1]
```diff
@@ -1880,6 +1880,16 @@ namespace smt {
...
+
+        // axiom 2: The only (str.from-int N) that starts with a "0" is "0".
+        expr_ref zero(mk_string("0"), m);
+        // let (the result starts with a "0") be p
+        expr_ref p(u.str.mk_prefix(zero, ex), m);
+        // let (the result is "0") be q  
+        expr_ref q(ctx.mk_eq_atom(ex, zero), m);
+        // encoding: the result does NOT start with a "0" (~p) xor the result is "0" (q)
+        // ~p xor q == (~p or q) and (p or ~q)
+        assert_axiom(m.mk_and(m.mk_or(mk_not(m, p), q), m.mk_or(p, mk_not(m, q))));
```
Comment (mtrberzi) [inline src/smt/theory_str.cpp]: Is there a reason why the function form of `mk_not` was used and not the method on `ast_manager` (i.e. `m.mk_not(p)`)?

File: src/smt/theory_str.cpp [hunk 2]
```diff
@@ -1880,6 +1880,16 @@ namespace smt {
             SASSERT(axiom1);
             assert_axiom(axiom1);
         }
+
+        // axiom 2: The only (str.from-int N) that starts with a "0" is "0".
+        expr_ref zero(mk_string("0"), m);
+        // let (the result starts with a "0") be p
+        expr_ref p(u.str.mk_prefix(zero, ex), m);
```
Comment (mtrberzi) [inline src/smt/theory_str.cpp]: I would suggest using more descriptive variable names, as it will greatly help the next time this code needs to be debugged or modified.

**Comment by mtrberzi** [comment]
@FedericoAureliano I have some review comments for you when you are able to take a look.

File: src/smt/theory_str.cpp (hunk 1 above)
Comment (FedericoAureliano) [reply src/smt/theory_str.cpp]: To be consistent with the existing code (e.g. line 1877 right above).

**Comment by FedericoAureliano** [comment]
@mtrberzi fixed!
